name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t buster .
      - name: Run flake8
        run: docker run --rm --entrypoint flake8 buster
      - name: Run pytest
        run: docker run --rm --entrypoint pytest buster
